### ISSUE TITLE
Feature Request: DNS Server unbound

### ISSUE THREAD

**Issue by thew0mble** [mikaku/Monitorix#176]
The ability to get some stats from the unbound-control dns caching server similar to what you already with bind.

They provide instructions how to use munun, I would like to use Monitorix.
https://www.unbound.net/documentation/howto_statistics.html

**Comment by andrieslouw** [comment]
New link: https://nlnetlabs.nl/documentation/unbound/howto-statistics/

**Comment by mikaku** [comment]
@andrieslouwm, thanks.
As soon as I have a window of calm in my work, I'll include support for unbound.

**Comment by mikaku** [comment]
I don't use `unbound`, I use `bind` or `dnsmasq` instead, so I don't know how to make a simple zone with `unbound` to be able to get statistics.

Anyone is willing to send me a simple configuration file to make `unbound` running without many headaches?

**Comment by andrieslouw** [comment]
Example config to use as caching server for OpenDNS (forwards all queries to OpenDNS servers):
[unbound.conf.txt](https://github.com/mikaku/Monitorix/files/3678349/unbound.conf.txt)

With this you can use 127.0.0.1 as your nameserver in /etc/resolv.conf

Please also read: https://wiki.archlinux.org/index.php/unbound#Setting_up_unbound-control

**Comment by andrieslouw** [comment]
Are there any instructions on how to write plug-ins? I see it's always in Perl, that's correct?
Do you have a template from which to create new plugins? Or is the code generated?

**Comment by IzzySoft** [comment]
Most simple config (out of an article I wrote for Heise about two years ago):

```
server:
    interface: 0.0.0.0
        access-control: 10.0.0.0/16 allow
        access-control: 127.0.0.0/8 allow
        access-control: 192.168.0.0/16 allow
        verbosity: 1

forward-zone:
      name: "."
      # definitely censor free & log free with DNSSEC Support:
      forward-addr: 84.200.69.80   # DNS Watch
      forward-addr: 84.200.70.40   # DNS Watch
      forward-addr: 91.239.100.100 # censurfridns.dk
      forward-addr: 89.233.43.71   # censurfridns.dk
```

Round-robin forwards all requests to DNS Watch/censurfridns, and allows to be queried from the four networks mentioned initially. If you want something more complex, building upon that, let me know. I can send you snippets for localzones, tags, views and ad-blocking configs. I do not use tags/views myself, but unbound serves my home network pretty neat – nicely reducing traffic and keeping data from many a kraken :rofl:

**Comment by mikaku** [comment]
@andrieslouw, I just wanted something more straightforward, thanks anyway.

>Are there any instructions on how to write plug-ins? I see it's always in Perl, that's correct?
Do you have a template from which to create new plugins? Or is the code generated?

No, the code is as simple as it's. There is not a template from where to start writing your own module. But, all modules follow the same code structure, variable names and all have a simple Perl syntax. So it shouldn't be difficult for anyone knowing a little of Perl to create its own module.

@IzzySoft, yeah, that's what I was looking for. Thanks!

**Comment by IzzySoft** [comment]
@mikaku you could even strip that down farther (e.g. kick out the 10.x network from access control if you don't use IPs in that range, or drop up to 3 forwarders) 😉 Absolutely stripped down, it could be something like

```
server:
    interface: 0.0.0.0
        access-control: 127.0.0.0/8 allow

forward-zone:
      name: "."
      forward-addr: 84.200.69.80   # DNS Watch
```

So it would only be available to localhost – and when the only `forward-addr` goes down, you're blind 😆 All else should revert to defaults. But that'd be a bit too much stripped down IMHO.
